version: '3.8'
services:
  frontend:
    build:
      context: ./frontEnd
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://<IP-адрес-бэкенда>:<порт>
    ports:
      - "3000:3000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend